# Render.com Configuration with MongoDB Atlas
# Build Command: npm install
# Start Command: npm start
# Environment: Node
# Node Version: 18

# Environment Variables Required:
# MONGODB_URI - MongoDB Atlas connection string
# PORT - Server port (automatically set by Render)

# Render will automatically:
# - Install dependencies with npm install
# - Start the server with npm start
# - Provide HTTPS SSL certificate
# - Set PORT environment variable
# - Enable auto-deploy from GitHub
# - Connect to MongoDB Atlas for data persistence

# MongoDB Atlas Features:
# - Real-time data persistence
# - Automatic backups
# - Scalable cloud database
# - No data loss on server restart
